### PR TITLE
store names can't have "." in them, because Mongo :)

### PR DESCRIPTION
**Pull request by andreivolt**

### CODE REVIEW

**Comment by aldeed** [comment]
I don't see any such restriction: http://docs.mongodb.org/manual/reference/limits/#Restriction-on-Collection-Names

But we should have checks for the other restrictions listed there. I think there may be mongo shell bugs related to dots and underscores in collection names, but it doesn't appear to be a true restriction.

**Comment by aldeed** [comment]
Oh, but I guess you're referring to the field name restriction because we also include it in a field name.

**Comment by andreivolt** [comment]
Yes, what I meant that I causes unintented behaviour, eg. for the `copies` property, a `set` operation with a '.' will create a nested object.

**Comment by aldeed** [comment]
Right.

**Pull request merged**
