### PR TITLE
Bringing general documentation forward

### PR DESCRIPTION
**Pull request by brylie**
The documentation for this project was at a point very extensive. It has since been reduced quite drastically. Lets build on the previous documentation, correcting things that have changed, rather than throwing away this extensive resource.

### CODE REVIEW

**Comment by wursttheke** [comment]
Hey @brylie! We're not throwing away anything. Instead we are refactoring / cleaning up the existing docs after the merge of the different packages into one Github repository. In fact I just added a first PR for updated docs: https://github.com/CollectionFS/Meteor-CollectionFS/pull/571.

We are also going to use the [Wiki](https://github.com/CollectionFS/Meteor-CollectionFS/issues/563) for extensive Examples and How-tos.

The progress is being tracked here: https://github.com/CollectionFS/Meteor-CollectionFS/issues/563

**Comment by brylie** [comment]
Ah, thanks @wursttheke :-)

**Comment by wursttheke** [comment]
README is now back online. :)

**Comment by raix** [comment]
Sweet :)

**Pull request closed without merging**
