### PR TITLE
About Meteor.publish

### PR DESCRIPTION
**Pull request by comerc**

### CODE REVIEW

**Comment by aldeed** [comment]
It depends on how your data is structured whether you can use Meteor.publish or need one of the join packages. This addition isn't very helpful as is since the room/messages example makes no sense here.

**Comment by comerc** [comment]
We add it, if I change example?

**Comment by aldeed** [comment]
Yes, if you can make an example that matches the others.

**Comment by comerc** [comment]
Ok, I corrected example.

**Pull request merged**
