### PR TITLE
onStored and onStoredCallback functions - return when file is fully stored.

### PR DESCRIPTION
**Pull request by okland**
(FS.File) Added onStored and onStoredCallback functions -
Function that return or call callback when file is fully stored in a specify storeName,
Needed in many cases - For example needed if wanted to save the direct link to a file on s3 when fully uploaded.

Moreover added option  on server to return url only when is fully stored in specified storedName.

### CODE REVIEW

**Comment by Neftedollar** [comment]
hi! What's problem with accepting this PR? Help needed?

**Comment by jlukic** [comment]
@aldeed Any chance to review this?

**Comment by Neftedollar** [comment]
Yaaaaay!!!

**Comment by raix** [comment]
Finally eh? :)

**Comment by fadomire** [comment]
how to use this ?

**Pull request merged**
