### PR TITLE
Added polyfill for IE base64 encoding btoa/atob

### PR DESCRIPTION
**Pull request by todda00**
PR to resolve https://github.com/CollectionFS/Meteor-CollectionFS/issues/515

Confirmed this is working on IE9, have not tried with IE8, but conceptually it should work.

### CODE REVIEW

**Comment by bompi88** [comment]
What is the status of this PR?

**Comment by andersottesen** [comment]
Still waiting for this with @bompi88 . Does not work in IE9

**Comment by todda00** [comment]
@aldeed : can this PR be merged in? I have been using this PR in production for a few months no with no issue.

**Comment by raix** [comment]
Thank you @todda00

**Pull request merged**
