### PR TITLE
Added eachFileFromPath helper function

### PR DESCRIPTION
**Pull request by rhyslbw**
- Based on FS.Utility.eachFile
- String passed to fs.readdir, with the results mapped to and array with the full path of each file in the directory, filtered using isFile()
- Each file then passed as the first param to the supplied function
- If an error is thrown as part of the readdir, a Meteor.Error is thrown.

### CODE REVIEW

**Comment by aldeed** [comment]
@rhyslbw, if I were using this on the server, I would expect it to run the function synchronously (function is run for all files before the next line of code runs) because Meteor server code is synchronous, but currently this uses `fs.readdir` so it's async. I suggest you rewrite using `fs.readdirSync`. Other than that, it looks good to me.

**Comment by rhyslbw** [comment]
Isn't readdir just unblocking the filesystem interaction since the result is an array of all the paths that are then mapped and filtered into the supplied callback?

**Comment by aldeed** [comment]
The supplied function isn't really a "callback" per se. It's just an iterator function which your function will call 0 or more times. The question is whether we should call it for all the files before or after we return from this function. As is, it will not call the iterator function until after the current function returns.

I'm not positive about this, but you could test it fairly easily with

```js
console.log(1);

FS.Utility.eachFileFromPath('/path-with-one-file', function () {
  console.log(2);
});

console.log(3);
```

I think it will log 1, 3, 2. I'm suggesting it should be 1, 2, 3 instead, because my next line might assume that the function has already been called.

cc @raix

**Comment by rhyslbw** [comment]
Right I see the issue, it's basically an async function without a callback. Your assumption is correct, 1,3,2. Sounds like readdirSync is going to be the best way to handle this given Meteor's sync style. I'll make the changes

**Comment by raix** [comment]
Should this api be on SA level instead of utils?
It's a really good queation about iterator callbacks. Fibers only allow the callback call once, so if async (like streams/events) we would need a convertion.

**Comment by rhyslbw** [comment]
I'm using it to insert files from the filesystem in the same way the eachFile function is used on the client.

This npm package might be a good option for improving this utility and a more powerful Filesystem API
https://www.npmjs.com/package/fstream

**Comment by rhyslbw** [comment]
I've just committed the changes as discussed relating to the readdir function

**Comment by aldeed** [comment]
@rhyslbw this looks good, but your other changes ended up in this PR. Each PR should be done in a separate branch in your fork. I merged eachFileFromPath manually in `devel` branch.

Can you update the devel branch in your fork, make a new branch off that for your worker changes, and then do a new PR to pull from your worker branch into CFS:devel?

**Comment by rhyslbw** [comment]
Sorry @aldeed, I sort that today

**Comment by rhyslbw** [comment]
https://github.com/CollectionFS/Meteor-CollectionFS/pull/667

**Pull request closed without merging**
