### PR TITLE
Readme clarity about allow download

### PR DESCRIPTION
**Pull request by KristerV**
makes #587 better

### CODE REVIEW

**Comment by KristerV** [comment]
I've added a quick start tutorial from medium, it's all-encompassing and is a great starter.

**Comment by aldeed** [comment]
Looks okay, but I don't think we want to say we recommend GridFS. I usually use S3, and filesystem works fine for some situations. We may just need to be clearer about the reasons why you might want to avoid filesystem. (We have one note about it [here](https://github.com/CollectionFS/Meteor-CollectionFS/tree/master/packages/filesystem#important-note) but could be more explanation.) @raix?

**Comment by raix** [comment]
Agree we only have a note about the filesystem SA when using it on *.meteor.com - Recommendations depend on the system folks are building regarding scalability/features/integrations etc. a lot of pro/cons.

We will have recommendations later on - but, I'm trying not to be opinionated about it.

**Comment by aldeed** [comment]
I merged and removed the "recommended" part. We'll work separately to clarify the pros and cons of each storage adapter.

**Comment by KristerV** [comment]
cool

**Pull request merged**
